export const enum AgenciesActionTypes {
  FETCH_AGENCIES_REQUEST = 'FETCH_AGENCIES_REQUEST',
  FETCH_AGENCIES_SUCCESS = 'FETCH_AGENCIES_SUCCESS',
  FETCH_AGENCIES_FAILURE = 'FETCH_AGENCIES_FAILURE ',
}
